Refactor user administration features
NethServer/nethsecurity-ui pull request #294
Opened 2024-06-11 10:48 UTC by stephdl

This pull request refactors the user administration features in the codebase. It includes the following changes:

- Added an administrator user tooltip to the translation.json file.

- Added an admin toggle to the CreateOrEditUserDrawer.vue file.

- Added an admin flag to the User type in the UsersDatabaseManager.vue file.

These changes improve the user administration functionality and provide better control over user privileges.

2024-06-12 09:14 UTC, andre8244 commented on public/i18n/en/translation.json
> +      "administrator_tooltip": "The administrator user is a special user that can access all services and features of the system. This user is not subject to the VPN service restrictions.",
```suggestion
      "administrator_tooltip": "A user promoted to administrator can access the administration web interface and configure this unit.",
```

2024-06-12 09:49 UTC, andre8244 approved these changes
Just an unused import to remove

2024-06-12 09:49 UTC, andre8244 commented on src/components/standalone/users_database/UsersTable.vue
> +  NeBadge
This import can be removed

2024-06-13 13:59 UTC, Tbaile requested changes

2024-06-13 13:59 UTC, Tbaile commented on src/components/standalone/users_database/UsersTable.vue
> +  remove_admin: [item: User]
Consider following this format for events (generally for everything in Vue): https://vuejs.org/guide/components/events.html#emitting-and-listening-to-events

2024-06-17 07:18 UTC, Tbaile commented on src/components/standalone/users_database/UsersDatabaseManager.vue
> +}
Are there situations where an error can be returned?

2024-06-17 08:27 UTC, Tbaile commented on src/components/standalone/users_database/UsersDatabaseManager.vue
> +}
Worry not! Was just asking if a forseeable error might be returned, since it's not the case, we are all good!

2024-06-17 08:28 UTC, Tbaile approved these changes

2024-06-17 12:47 UTC, gsanchietti approved these changes
The commit history is not good: a unique commit with feature tag should be enough.

2024-06-17 13:33 UTC, merged