Add length validation for name rule
NethServer/nethsecurity-ui pull request #397
Opened 2024-10-09 10:49 UTC by stephdl

This pull request adds a length validation for the name rule in the `useRuleForm.ts` file. The validation ensures that the name is not more than 12 characters long. This validation is implemented in the `validateLengthNotMore12` function in the `validation.ts` file.

https://github.com/NethServer/nethsecurity/issues/835

2024-10-09 13:05 UTC, Tbaile commented
Shall we add a configurable validation rule? Such as "max {n} characters" are available?

2024-10-10 06:26 UTC, gsanchietti commented
I'm going to leave the review to @Tbaile because I do not know enough the components.

2024-10-10 09:54 UTC, Tbaile requested changes
While thinking about adding a max length rule, it appears that in this case it's correct to use this kind of validation (due to iptables being a psycho regarding the naming schemes). Just a few touches and this can be pushed to the 8.4 roadmap!

2024-10-10 09:54 UTC, Tbaile commented on src/composables/useRuleForm.ts
> +    }
To see how to handle the translation process of these cases in a more clean way: https://github.com/NethServer/nethsecurity-ui/blob/898bc8593bc8cbdb212ff84e604d0adf4af9ad77/src/components/standalone/interfaces_and_devices/ConfigureDeviceDrawer.vue#L663

2024-10-15 07:30 UTC, Tbaile requested changes
For parameters don't return additional value in the MessageBox, use the `i18Params`

2024-10-15 12:33 UTC, Tbaile approved these changes

2024-10-15 12:33 UTC, Tbaile commented
Will merge after next NethSecurity release

2024-10-17 14:24 UTC, merged