feat: added netify interface
NethServer/nethsecurity-ui pull request #467
Opened 2024-12-27 15:47 UTC by stephdl

Introduce a new monitoring component for Netify Informatics, including necessary routes and translations for integration into the application.

https://github.com/NethServer/nethsecurity/issues/981

https://github.com/user-attachments/assets/514fb61d-4944-41c5-9798-96983b63f68f

https://github.com/user-attachments/assets/bc35f876-c94d-44d2-a8a1-96d9e810660d

https://github.com/user-attachments/assets/18dd855c-1f9e-482a-a1df-79c69e5ee8ad

2025-01-07 08:15 UTC, Tbaile requested changes

2025-01-07 08:15 UTC, Tbaile commented on src/components/standalone/monitoring/NetifyInformaticsContent.vue
Please stick to the camelCase format for both variables and functions in the JS/TS space.

2025-01-07 08:15 UTC, Tbaile commented on src/components/standalone/monitoring/NetifyInformaticsContent.vue
> +}
While I don't like the approach of multiple error handling like this, I can allow it, but it completely loses effectiveness when there are multiple variables for each error, is redundant (and don't assign them like that, while TS allows it, it's really a nasty approach)

2025-01-07 08:15 UTC, Tbaile commented on src/components/standalone/monitoring/NetifyInformaticsContent.vue
> +      loading.value = false
Put this into a "finally" clause, this way the loading always removes itself after the request

2025-01-07 08:15 UTC, Tbaile commented on src/components/standalone/monitoring/NetifyInformaticsContent.vue
> +    isError.value = true
Maybe is better to define the `error` object as nullable, and check for nullable if there's an error set, otherwise we assume state is good

2025-01-07 08:15 UTC, Tbaile commented on src/components/standalone/monitoring/NetifyInformaticsContent.vue
> +        </i18n-t>
Use `t` object in template for every localized string
```suggestion
        <p>{{ t('standalone.netify_informatics.content_description') }}</p
```

2025-01-07 08:15 UTC, Tbaile commented on src/components/standalone/monitoring/NetifyInformaticsContent.vue
> +            <FontAwesomeIcon :icon="['fas', 'arrow-up-right-from-square']" aria-hidden="true" />
Import the icon and use it directly in the `:icon` prop, [like here](https://github.com/NethServer/nethsecurity-ui/blob/dbf54e0203a294860a1a3f974ec599bc5aa2d6d2/src/components/controller/users/UsersTable.vue#L86)

2025-01-07 08:15 UTC, Tbaile commented on src/components/standalone/monitoring/NetifyInformaticsContent.vue
> +              <font-awesome-icon :icon="['fas', 'copy']" class="h-4 w-4" aria-hidden="true" />
Same as above, also:
```suggestion
              <FontAwesomeIcon :icon="['fas', 'copy']" class="h-4 w-4" aria-hidden="true" />
```

2025-01-07 08:31 UTC, gsanchietti reviewed
Minor label rewording.

2025-01-07 08:31 UTC, gsanchietti commented on src/i18n/en/translation.json
> +      "uuid": "UUID",
```suggestion
      "uuid": "Agent UUID",
```

2025-01-07 08:31 UTC, gsanchietti commented on src/i18n/en/translation.json
> +      "content_description": "Netify Informatics is a third-party cloud service that utilizes analytics and AI to convert local DPI metadata obtained from NethSecurity into high-level network intelli
```suggestion
      "content_description": "Netify Informatics is a third-party cloud service that utilizes analytics and AI to convert local DPI metadata obtained from NethSecurity into high-level network intelligence. Copy the Agent UUID, then access Netify site and proceed with provision agent wizard.",
```

2025-01-07 08:40 UTC, Tbaile commented on src/views/standalone/monitoring/NetifyInformaticsView.vue
Agree when there are multiple components, otherwise you can safely add everything in the page (due to the dynamic import of the router, everything will be pulled only when needed :magic_wand:)

2025-01-07 09:52 UTC, andre8244 requested changes

2025-01-07 09:52 UTC, andre8244 commented on src/components/standalone/monitoring/NetifyInformaticsContent.vue
> +        <NeFormItemLabel>{{ t('standalone.netify_informatics.status') }}</NeFormItemLabel>
This label has an incorrect spacing from the toggle. Let's use `topLabel` prop of `NeToggle` component, see https://nethesis.github.io/vue-components/?path=/story/netoggle--with-top-label

2025-01-07 09:52 UTC, andre8244 commented on src/components/standalone/monitoring/NetifyInformaticsContent.vue
> +        <NeButton kind="tertiary" size="lg" @click="openDashboard()" class="ml-2 shrink-0">
Let's fix vertical spacing and use `NeLink` instead (in general: NeButton is for actions, NeLink is for simple links). See https://github.com/NethServer/nethsecurity-ui/blob/main/src/components/standalone/backup_and_restore/MigrationContent.vue#L39-L44

2025-01-07 09:52 UTC, andre8244 commented on src/components/standalone/monitoring/NetifyInformaticsContent.vue
> +          <NeButton kind="tertiary" size="sm" @click="copyUuid" class="ml-2.5 mt-8">
"Copied to clipboard" badge should be a tooltip instead. A bit of rework is needed, let's replace this NeButton and the NeBadge with:

```suggestion
          <NeTooltip v-if="justCopied" triggerEvent="mouseenter focus" placement="top-start">
            <template #trigger>
              <NeButton kind="secondary" size="md" @click="copyUuid" class="mb-px ml-2.5">
                <template #prefix>
                  <FontAwesomeIcon :icon="faCopy" class="h-4 w-4" aria-hidden="true" />
                </template>
                {{ t('standalone.netify_informatics.copy') }}
              </NeButton>
            </template>
            <template #content>
              {{ t('standalone.netify_informatics.copied_to_clipboard') }}
            </template>
          </NeTooltip>
          <NeButton v-else kind="secondary" size="md" @click="copyUuid" class="mb-px ml-2.5">
            <template #prefix>
              <FontAwesomeIcon :icon="faCopy" class="h-4 w-4" aria-hidden="true" />
            </template>
            {{ t('standalone.netify_informatics.copy') }}
          </NeButton>
```

2025-01-07 09:52 UTC, andre8244 commented on src/components/standalone/monitoring/NetifyInformaticsContent.vue
> +        <div class="relative flex items-center gap-2">
```suggestion
        <div class="relative flex items-end gap-2">
```

2025-01-07 09:52 UTC, andre8244 commented on src/i18n/en/translation.json
> +      "netify_informatics_enable_description": "Metadata sending is now active. Configuration saved successfully",
```suggestion
      "netify_informatics_enable_description": "Metadata sending is now active",
```

2025-01-07 09:52 UTC, andre8244 commented on src/i18n/en/translation.json
> +      "netify_informatics_disable_description": "Metadata sending has been disabled. Configuration saved successfully",
```suggestion
      "netify_informatics_disable_description": "Metadata sending has been disabled",
```

2025-01-07 09:52 UTC, andre8244 commented on src/components/standalone/monitoring/NetifyInformaticsContent.vue
> +  NeBadge
```suggestion
  NeTooltip
```

2025-01-07 10:51 UTC, stephdl commented on src/components/standalone/monitoring/NetifyInformaticsContent.vue
> +    isError.value = true
happy to do with another way tommaso, but it is a common way to set to true when we have an error, what do you think @andre8244

2025-01-07 10:57 UTC, Tbaile commented on src/components/standalone/monitoring/NetifyInformaticsContent.vue
> +    isError.value = true
Yes, but in this case the error information is decoupled, during coding if `isError` is not set during an error no message is displayed even if the error is thrown and saved. 
A solution can be of the following:
```ts
const error: Ref<ErrorObject?> = ref()
```
This tells the code that the error can be `undefined` and you can check for it

2025-01-07 11:25 UTC, andre8244 commented on src/components/standalone/monitoring/NetifyInformaticsContent.vue
> +    isError.value = true
Let's find the quickest solution, but IMHO there are too many variables and typescript types for a simple form with only a toggle :confused: If you got stuck I suggest to use the same variables pattern of other pages (e.g. NatHelpers.vue is a recent and simple page)

2025-01-07 11:26 UTC, Tbaile requested changes

2025-01-07 11:26 UTC, Tbaile commented on src/components/standalone/monitoring/NetifyInformaticsContent.vue
> +})
Nesting is not needed, just adds overhead

```suggestion
const status = ref(false)
cost uuid = ref('')
```

2025-01-07 11:26 UTC, Tbaile commented on src/components/standalone/monitoring/NetifyInformaticsContent.vue
> +const errorSaving = ref({ ...objError })
This part is really hard to understand

`error` is effectively not used, if not for line 162, however the value is never set, so what is this for?
`errorLoadingConfiguration` and `errorSaving` are basically the same, there's no difference between them, they can be the same value

2025-01-07 11:26 UTC, Tbaile commented on src/components/standalone/monitoring/NetifyInformaticsContent.vue
> +            :invalid-message="error.uuid"
A read-only value, can be invalid?

2025-01-07 11:26 UTC, Tbaile commented on src/components/standalone/monitoring/NetifyInformaticsContent.vue
> +          :topLabel="t('standalone.netify_informatics.status')"
```suggestion
          :top-label="t('standalone.netify_informatics.status')"
```

2025-01-07 11:26 UTC, Tbaile commented on src/components/standalone/monitoring/NetifyInformaticsContent.vue
> +          @update:model-value="handleSaveAutomaticToggle"
This is dangerous, you're overriding the [vue default compilation](https://vuejs.org/guide/components/v-model.html#under-the-hood).

I'd suggest the usage of `watch` instead, if you used it before and the trigger was not working, could be cause of the missing [deep directive](https://vuejs.org/guide/essentials/watchers.html#deep-watchers), which if you simplify the `refs` this is not needed anymore.

2025-01-07 13:39 UTC, gsanchietti reviewed
Labels are good for me.

2025-01-07 16:35 UTC, Tbaile submitted a review, later dismissed
Remember to squash and remove the body of the commit, title is fine the one on the PR

2025-01-07 16:52 UTC, andre8244 submitted a review, later dismissed
Ok, just a minor style fix

2025-01-08 09:52 UTC, andre8244 approved these changes

2025-01-08 09:55 UTC, gsanchietti approved these changes

2025-01-08 09:56 UTC, merged